graph LR
    client1[WebApp]-. HTTPS .-> loadbalancer[Service];

    subgraph Azure[Microsoft Azure]

        loadbalancer[Load Balancer] .-> ingress;


        subgraph aks["Azure Kubernetes Service"]
            ingress[Ingress];

            ingress --> service1;
            ingress --> service2;
            ingress --> service3;

            service1 .-> pod11;
            service1 .-> pod12;

            service2 .-> pod21;
            service2 .-> pod22;
            service2 .-> pod23;

            service3 .-> pod31;
            service3 .-> pod32;

            subgraph nodepool[Node Pool]
                subgraph node1
                    subgraph deployment1
                        pod11;
                        pod12;
                    end
                end

                subgraph node2
                    subgraph deployment2
                        pod21;
                        pod22;
                        pod23;
                    end
                end
            end

            subgraph node3
                subgraph deployment3
                    pod31;
                    pod32;
                end
            end

        end

        pod11 .-> db1[Azure CosmosDB];
        pod12 .-> db1;

        pod21 .-> db2[Azure CosmosDB];
        pod22 .-> db2;
        pod23 .-> db2;

        pod31 .-> db3[Azure CosmosDB];
        pod32 .-> db3;

        pod11 .-> kv[Azure Key Vault];
        pod12 .-> kv;

        pod21 .-> kv;
        pod22 .-> kv;
        pod23 .-> kv;

        pod31 .-> kv;
        pod32 .-> kv;

        pod11 .-> asb[Azure Service Bus];
        pod12 .-> asb;

        pod21 .-> asb;
        pod22 .-> asb;
        pod23 .-> asb;

        pod31 .-> asb;
        pod32 .-> asb;

        aks .-> cr[Container Registry];
    end

    classDef plain fill:#ddd,stroke:#fff,stroke-width:4px,color:#000;
    classDef cluster fill:#fff,stroke:#bbb,stroke-width:2px,color:#326ce5;
    class client1,client2,client3,client4 plain;
    class cluster cluster;